export const axiosResponseData = [
  {
    url: "https://api.github.com/repos/facebook/react/issues/28815",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url: "https://api.github.com/repos/facebook/react/issues/28815/labels{/name}",
    comments_url: "https://api.github.com/repos/facebook/react/issues/28815/comments",
    events_url: "https://api.github.com/repos/facebook/react/issues/28815/events",
    html_url: "https://github.com/facebook/react/pull/28815",
    id: 2236175359,
    node_id: "PR_kwDOAJy2Ks5sRwGt",
    number: 28815,
    title: "mocked_axios_response",
    user: {
      login: "gnoff",
      id: 2716369,
      node_id: "MDQ6VXNlcjI3MTYzNjk=",
      avatar_url: "https://avatars.githubusercontent.com/u/2716369?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/gnoff",
      html_url: "https://github.com/gnoff",
      followers_url: "https://api.github.com/users/gnoff/followers",
      following_url: "https://api.github.com/users/gnoff/following{/other_user}",
      gists_url: "https://api.github.com/users/gnoff/gists{/gist_id}",
      starred_url: "https://api.github.com/users/gnoff/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/gnoff/subscriptions",
      organizations_url: "https://api.github.com/users/gnoff/orgs",
      repos_url: "https://api.github.com/users/gnoff/repos",
      events_url: "https://api.github.com/users/gnoff/events{/privacy}",
      received_events_url: "https://api.github.com/users/gnoff/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2024-04-10T18:20:19Z",
    updated_at: "2024-04-10T18:29:28Z",
    closed_at: null,
    author_association: "COLLABORATOR",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/28815",
      html_url: "https://github.com/facebook/react/pull/28815",
      diff_url: "https://github.com/facebook/react/pull/28815.diff",
      patch_url: "https://github.com/facebook/react/pull/28815.patch",
      merged_at: null,
    },
    body: "`<noscript>` scopes should be considered inert from the perspective of Fizz since we assume they'll only be used in rare and adverse circumstances. When we added preload support for img tags we did not include the noscript scope check in the opt-out for preloading. This change adds it in\r\n\r\nfixes: #27910",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/28815/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/facebook/react/issues/28815/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/28814",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url: "https://api.github.com/repos/facebook/react/issues/28814/labels{/name}",
    comments_url: "https://api.github.com/repos/facebook/react/issues/28814/comments",
    events_url: "https://api.github.com/repos/facebook/react/issues/28814/events",
    html_url: "https://github.com/facebook/react/pull/28814",
    id: 2236137286,
    node_id: "PR_kwDOAJy2Ks5sRnyr",
    number: 28814,
    title: "[tests] add assertLog for legacy mode tests",
    user: {
      login: "rickhanlonii",
      id: 2440089,
      node_id: "MDQ6VXNlcjI0NDAwODk=",
      avatar_url: "https://avatars.githubusercontent.com/u/2440089?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rickhanlonii",
      html_url: "https://github.com/rickhanlonii",
      followers_url: "https://api.github.com/users/rickhanlonii/followers",
      following_url: "https://api.github.com/users/rickhanlonii/following{/other_user}",
      gists_url: "https://api.github.com/users/rickhanlonii/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rickhanlonii/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rickhanlonii/subscriptions",
      organizations_url: "https://api.github.com/users/rickhanlonii/orgs",
      repos_url: "https://api.github.com/users/rickhanlonii/repos",
      events_url: "https://api.github.com/users/rickhanlonii/events{/privacy}",
      received_events_url: "https://api.github.com/users/rickhanlonii/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2024-04-10T17:54:55Z",
    updated_at: "2024-04-10T18:02:08Z",
    closed_at: "2024-04-10T18:01:59Z",
    author_association: "MEMBER",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/28814",
      html_url: "https://github.com/facebook/react/pull/28814",
      diff_url: "https://github.com/facebook/react/pull/28814.diff",
      patch_url: "https://github.com/facebook/react/pull/28814.patch",
      merged_at: "2024-04-10T18:01:59Z",
    },
    body: "A few more tests for https://github.com/facebook/react/pull/28737",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/28814/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/facebook/react/issues/28814/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/28813",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url: "https://api.github.com/repos/facebook/react/issues/28813/labels{/name}",
    comments_url: "https://api.github.com/repos/facebook/react/issues/28813/comments",
    events_url: "https://api.github.com/repos/facebook/react/issues/28813/events",
    html_url: "https://github.com/facebook/react/pull/28813",
    id: 2236094101,
    node_id: "PR_kwDOAJy2Ks5sReT2",
    number: 28813,
    title: "Rename the react.element symbol to react.transitional.element",
    user: {
      login: "sebmarkbage",
      id: 63648,
      node_id: "MDQ6VXNlcjYzNjQ4",
      avatar_url: "https://avatars.githubusercontent.com/u/63648?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/sebmarkbage",
      html_url: "https://github.com/sebmarkbage",
      followers_url: "https://api.github.com/users/sebmarkbage/followers",
      following_url: "https://api.github.com/users/sebmarkbage/following{/other_user}",
      gists_url: "https://api.github.com/users/sebmarkbage/gists{/gist_id}",
      starred_url: "https://api.github.com/users/sebmarkbage/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/sebmarkbage/subscriptions",
      organizations_url: "https://api.github.com/users/sebmarkbage/orgs",
      repos_url: "https://api.github.com/users/sebmarkbage/repos",
      events_url: "https://api.github.com/users/sebmarkbage/events{/privacy}",
      received_events_url: "https://api.github.com/users/sebmarkbage/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 5,
    created_at: "2024-04-10T17:25:42Z",
    updated_at: "2024-04-10T18:38:20Z",
    closed_at: null,
    author_association: "COLLABORATOR",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/28813",
      html_url: "https://github.com/facebook/react/pull/28813",
      diff_url: "https://github.com/facebook/react/pull/28813.diff",
      patch_url: "https://github.com/facebook/react/pull/28813.patch",
      merged_at: null,
    },
    body: "We have changed the shape (and the runtime) of React Elements. To help avoid precompiled or inlined JSX having subtle breakages or deopting hidden classes, I renamed the symbol so that we can early error if private implementation details are used or mismatching versions are used.\r\n\r\nWhy \"transitional\"? Well, because this is not the last time we'll change the shape. This is just a stepping stone to removing the `ref` field on the elements in the next version so we'll likely have to do it again.\r\n",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/28813/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/facebook/react/issues/28813/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/28812",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url: "https://api.github.com/repos/facebook/react/issues/28812/labels{/name}",
    comments_url: "https://api.github.com/repos/facebook/react/issues/28812/comments",
    events_url: "https://api.github.com/repos/facebook/react/issues/28812/events",
    html_url: "https://github.com/facebook/react/pull/28812",
    id: 2235875915,
    node_id: "PR_kwDOAJy2Ks5sQuIi",
    number: 28812,
    title: "Remove Scheduler.log from ReactSuspenseFuzz-test",
    user: {
      login: "rickhanlonii",
      id: 2440089,
      node_id: "MDQ6VXNlcjI0NDAwODk=",
      avatar_url: "https://avatars.githubusercontent.com/u/2440089?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rickhanlonii",
      html_url: "https://github.com/rickhanlonii",
      followers_url: "https://api.github.com/users/rickhanlonii/followers",
      following_url: "https://api.github.com/users/rickhanlonii/following{/other_user}",
      gists_url: "https://api.github.com/users/rickhanlonii/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rickhanlonii/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rickhanlonii/subscriptions",
      organizations_url: "https://api.github.com/users/rickhanlonii/orgs",
      repos_url: "https://api.github.com/users/rickhanlonii/repos",
      events_url: "https://api.github.com/users/rickhanlonii/events{/privacy}",
      received_events_url: "https://api.github.com/users/rickhanlonii/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2024-04-10T15:25:35Z",
    updated_at: "2024-04-10T15:40:25Z",
    closed_at: "2024-04-10T15:40:22Z",
    author_association: "MEMBER",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/28812",
      html_url: "https://github.com/facebook/react/pull/28812",
      diff_url: "https://github.com/facebook/react/pull/28812.diff",
      patch_url: "https://github.com/facebook/react/pull/28812.patch",
      merged_at: "2024-04-10T15:40:22Z",
    },
    body: "These test don't `assertLog` or `waitFor` so we don't need to `Scheduler.log`. Ideally we would, but since they're fuzzers it's a bit difficult to know what the expected log is from the helper.\r\n\r\nSince this doesn't regress current test behavior, we can improve them after this to unblock https://github.com/facebook/react/pull/28737",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/28812/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/facebook/react/issues/28812/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/28811",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url: "https://api.github.com/repos/facebook/react/issues/28811/labels{/name}",
    comments_url: "https://api.github.com/repos/facebook/react/issues/28811/comments",
    events_url: "https://api.github.com/repos/facebook/react/issues/28811/events",
    html_url: "https://github.com/facebook/react/pull/28811",
    id: 2235751671,
    node_id: "PR_kwDOAJy2Ks5sQSg7",
    number: 28811,
    title: "Hardcode disableIEWorkarounds for www",
    user: {
      login: "rickhanlonii",
      id: 2440089,
      node_id: "MDQ6VXNlcjI0NDAwODk=",
      avatar_url: "https://avatars.githubusercontent.com/u/2440089?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rickhanlonii",
      html_url: "https://github.com/rickhanlonii",
      followers_url: "https://api.github.com/users/rickhanlonii/followers",
      following_url: "https://api.github.com/users/rickhanlonii/following{/other_user}",
      gists_url: "https://api.github.com/users/rickhanlonii/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rickhanlonii/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rickhanlonii/subscriptions",
      organizations_url: "https://api.github.com/users/rickhanlonii/orgs",
      repos_url: "https://api.github.com/users/rickhanlonii/repos",
      events_url: "https://api.github.com/users/rickhanlonii/events{/privacy}",
      received_events_url: "https://api.github.com/users/rickhanlonii/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "closed",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2024-04-10T14:32:37Z",
    updated_at: "2024-04-10T15:14:36Z",
    closed_at: "2024-04-10T15:14:33Z",
    author_association: "MEMBER",
    active_lock_reason: null,
    draft: false,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/28811",
      html_url: "https://github.com/facebook/react/pull/28811",
      diff_url: "https://github.com/facebook/react/pull/28811.diff",
      patch_url: "https://github.com/facebook/react/pull/28811.patch",
      merged_at: "2024-04-10T15:14:33Z",
    },
    body: "This has landed and is true everywhere, but let's keep the flag until it lands in the stable release.",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/28811/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/facebook/react/issues/28811/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
  {
    url: "https://api.github.com/repos/facebook/react/issues/28810",
    repository_url: "https://api.github.com/repos/facebook/react",
    labels_url: "https://api.github.com/repos/facebook/react/issues/28810/labels{/name}",
    comments_url: "https://api.github.com/repos/facebook/react/issues/28810/comments",
    events_url: "https://api.github.com/repos/facebook/react/issues/28810/events",
    html_url: "https://github.com/facebook/react/pull/28810",
    id: 2235159494,
    node_id: "PR_kwDOAJy2Ks5sOSWk",
    number: 28810,
    title: "Reconciler: Don't retry synchronous render",
    user: {
      login: "eps1lon",
      id: 12292047,
      node_id: "MDQ6VXNlcjEyMjkyMDQ3",
      avatar_url: "https://avatars.githubusercontent.com/u/12292047?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/eps1lon",
      html_url: "https://github.com/eps1lon",
      followers_url: "https://api.github.com/users/eps1lon/followers",
      following_url: "https://api.github.com/users/eps1lon/following{/other_user}",
      gists_url: "https://api.github.com/users/eps1lon/gists{/gist_id}",
      starred_url: "https://api.github.com/users/eps1lon/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/eps1lon/subscriptions",
      organizations_url: "https://api.github.com/users/eps1lon/orgs",
      repos_url: "https://api.github.com/users/eps1lon/repos",
      events_url: "https://api.github.com/users/eps1lon/events{/privacy}",
      received_events_url: "https://api.github.com/users/eps1lon/received_events",
      type: "User",
      site_admin: false,
    },
    labels: [
      {
        id: 196858374,
        node_id: "MDU6TGFiZWwxOTY4NTgzNzQ=",
        url: "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
        name: "CLA Signed",
        color: "e7e7e7",
        default: false,
        description: null,
      },
      {
        id: 1775958285,
        node_id: "MDU6TGFiZWwxNzc1OTU4Mjg1",
        url: "https://api.github.com/repos/facebook/react/labels/React%20Core%20Team",
        name: "React Core Team",
        color: "9149d1",
        default: false,
        description: "Opened by a member of the React Core Team",
      },
    ],
    state: "open",
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: "2024-04-10T09:36:03Z",
    updated_at: "2024-04-10T17:33:04Z",
    closed_at: null,
    author_association: "COLLABORATOR",
    active_lock_reason: null,
    draft: true,
    pull_request: {
      url: "https://api.github.com/repos/facebook/react/pulls/28810",
      html_url: "https://github.com/facebook/react/pull/28810",
      diff_url: "https://github.com/facebook/react/pull/28810.diff",
      patch_url: "https://github.com/facebook/react/pull/28810.patch",
      merged_at: null,
    },
    body: "\r\n## Summary\r\n\r\nIn https://github.com/facebook/react/pull/13041 we started retrying the render synchronously if  a render threw during a concurrent render. However, this also applied to synchronous renders which should help very rarely since we don't support mutations during render. The original PR even explicitly said that a synchronous render should not be retried. \r\n\r\nA lot of tests asserted on the retry even though their render was sync i.e. not wrapped in `startTransition`.\r\n\r\nI originally caught this while investigating [duplicate host instance creation](https://github.com/facebook/react/issues/26518) in error boundary fallbacks which seems more off.\r\n\r\n## How did you test this change?\r\n\r\n- [ ] Codesandbox in https://github.com/facebook/react/issues/26518 no longer calls `document.createElement` twice \r\n- Adjusted tests to not assert that sync render retries\r\n",
    reactions: {
      url: "https://api.github.com/repos/facebook/react/issues/28810/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url: "https://api.github.com/repos/facebook/react/issues/28810/timeline",
    performed_via_github_app: null,
    state_reason: null,
  },
];
